version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    networks:
      - network
    ports:
      - 9876:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d/scripts
      - ./data:/docker-entrypoint-initdb.d/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - TZ=${TZ:-Europe/Luxembourg}
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8228:80"
    networks:
      - network
    environment:
      - TZ=${TZ:-Europe/Luxembourg}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-postgres@postgres.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-postgres}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
  postgres-data:
  pgadmin-data:
networks:
  network:
    driver: "bridge"